version: "3.9"
services:
  mongo_db:
    container_name: graph_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
